#!/usr/bin/env ruby
# frozen_string_literal: true

records = []

[0, 37, 100, 40].each do |c|
  records << { c: c.to_f, f: (c.to_f * (9 / 5)) + 32 }
end

[98.6, 65, 100].each do |f|
  records << { c: ((f.to_f - 32) * (5 / 9)), f: f.to_f }
end

records.sort! do |a, b|
  a[:f] <=> b[:f]
end

puts records

File.open('index.html', 'w') do |f|
  f.write "<!doctype html>
  <html lang=en-US>
    <head>
      <meta charset=UTF-8>
      <meta name=viewport content=\"width=device-width, initial-scale=1\">
      <title>Temperature</title>
      <link rel=stylesheet href=styles.css>
    </head>
    <body>
    <main>"
  f.write '<table>'
  f.write '<thead><tr><th>Celsius</th><th>Fahrenheit</th></tr>'
  f.write '</thead>'
  f.write '<tbody>'
  records.each do |record|
    f.write "<tr><td>#{record[:c]}</td><td>#{record[:f]}</td></tr>"
  end
  f.write '</tbody>'
  f.write '</table>'
  f.write '</main></body></html>'
end

`tidy --indent-spaces 2 --tidy-mark no -indent -wrap 0 -modify -quiet index.html`
